version: '3'
services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
        - '3306:3306'
    expose:
        - '3306'
    networks:
        - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
        - mariadb 
    ports:
        - '9000:9000'
    networks:
        - inception
    volumes:
        - wordpress_volume:/var/www/html
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - WP_DB_ADMIN=${WP_DB_ADMIN}
        - WP_DB_HOST=${WP_DB_HOST}
        - WP_URL=${WP_URL}
        - WP_TITLE=${WP_TITLE}
        - WP_ADM_MAIL=${WP_ADM_MAIL}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
        - WP_ADMIN_PASS=${WP_ADMIN_PASS}
        - WP_USER=${WP_USER}
        - WP_USER_MAIL=${WP_USER_MAIL}
        - WP_USER_PASS=${WP_USER_PASS}
    restart: always
  
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
        - wordpress
    ports:
        - '443:443'
    volumes:
        - ./requirements/nginx/conf:/etc/nginx/http.d
        - wordpress_volume:/var/www/html
    networks:
        - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_volume:
      driver_opts:
          type: none
          # device: /home/bbaatar/data/mariadb
          device: /Users/baigalmaa/work/temp/data/mariadb
          o: bind
  wordpress_volume:
      driver_opts:
         type: none
          # device: /home/bbaatar/data/wordpress
         device: /Users/baigalmaa/work/temp/data/wordpress
         o: bind

